### ISSUE TITLE
lcd1602.py does not initialize

### ISSUE THREAD

**Issue by MABeatty1978** [sunfounder/kepler-kit#1]
Using the code provided in https://docs.sunfounder.com/projects/kepler-kit/en/latest/pyproject/py_lcd.html

The library fails to initialize:
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "lcd1602.py", line 12, in __init__
  File "lcd1602.py", line 35, in send_command
  File "lcd1602.py", line 29, in write_word
OSError: [Errno 5] EIO

**Comment by MrBanane6969** [comment]
do you have 2 displays? if yes change to another one

![WhatsApp Bild 2023-04-07 um 16 40 08](https://user-images.githubusercontent.com/118633706/230627546-81118646-6b42-41da-8a9f-036f673dbcb6.jpg)

**Comment by kyuuinochi** [comment]
The reason may be:
1. The wiring is wrong and the I2C address cannot be recognized. Wiring needs to be checked.
2. The default i2c address of the old version lcd1602.py is 0x27, and the address of some LCDs is 0x3F. They updated the file 8 months ago to be compatible with both addresses. Just download the new version of the file and use it.
